# Generated by Django 4.2.14 on 2024-07-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyemail',
            name='email',
            field=models.EmailField(db_index=True, max_length=225, unique=True),
        ),
    ]
