# Generated by Django 4.2.14 on 2024-07-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_verifyemail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyemail',
            name='email',
            field=models.EmailField(db_index=True, max_length=50, unique=True),
        ),
    ]
